---
title: "ggplot2 Extension for Fun"
author: "Yawei Ge, Zhenzhen Chen, Weiquan Luo"
date: "3/22/2019"
output: rmarkdown::github_document
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Functions

### `geom_image`

Elephant and donkey

```{r, warning=FALSE, message=FALSE}
library(ggplot2)
library(ggfun)
library(dplyr)

ggplot(mtcars, aes(wt, mpg)) + geom_image()
```

### `stat_star`

Connect the central point to the farthest point

```{r}
madedata <- data.frame(x = rnorm(100, mean = 0, sd = 1),
                       y = rnorm(100, mean = 0, sd = 1))


ggplot(madedata, aes(x = x, y = y)) +
  geom_point() +
  stat_star(color = "red")
```

### `stat_arrowmap`

Forgive me for this

```{r, include=FALSE}
usmap <- map_data("state")
madedata_standard <- data.frame(region = unique(usmap$region), change = (runif(49)-0.5)*2,
                                stringsAsFactors = F)
madedata_standard <- madedata_standard %>%
  left_join(usmap,by = "region")
```

```{r}
madedata_standard %>%
  ggplot() +
  geom_path(aes(x = long, y = lat, group = group)) +
  stat_arrowmap(aes(x = long, y = lat, change = change, group = region))

```
